spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
  sql:
    init:
      schema-locations: classpath:schema.sql